name: thesis_py310
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py310h31b6992_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.12.1=pyhcf101f3_0
  - asttokens=3.0.0=py310h06a4308_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h6d33aed_0
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - blas=2.305=openblas
  - blas-devel=3.11.0=5_h1ea3ea9_openblas
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=py310h06a4308_0
  - cpython=3.10.19=py310hd8ed1ab_3
  - cuda-version=12.9=h4f385c5_3
  - datasets=4.5.0=pyhcf101f3_0
  - debugpy=1.8.16=py310hbdd6827_1
  - decorator=5.2.1=py310h06a4308_0
  - dill=0.4.0=pyhcf101f3_1
  - exceptiongroup=1.3.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - frozenlist=1.8.0=py310hbdd6827_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.0=py310h8c4cd34_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - ipykernel=6.31.0=py310h7040dfc_0
  - ipython=8.30.0=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.6.3=py310h06a4308_1
  - jupyter_core=5.9.1=py310h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.22.2=ha1258a1_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=22.0.0=h4253b2c_8_cpu
  - libarrow-acero=22.0.0=h635bf11_8_cpu
  - libarrow-compute=22.0.0=h8c2c5c3_8_cpu
  - libarrow-dataset=22.0.0=h635bf11_8_cpu
  - libarrow-substrait=22.0.0=h3f74fd7_8_cpu
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.18.0=hcf29cc6_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=h4751f2c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=22.0.0=h7376487_8_cpu
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.22.0=h454ac66_1
  - libutf8proc=2.11.3=hfe17d71_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxgboost=3.1.3=cuda129_h54c741a_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.10.0=h5888daf_1
  - matplotlib-inline=0.2.1=py310h06a4308_0
  - multidict=6.7.0=py310h3406613_0
  - multiprocess=0.70.18=py310h139afa4_2
  - nccl=2.29.2.1=h4d09622_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - nlohmann_json=3.12.0=h54a6638_1
  - openblas=0.3.30=pthreads_h6ec200e_4
  - openssl=3.6.1=h35e630c_1
  - orc=2.2.2=h19cb568_0
  - packaging=25.0=py310h06a4308_1
  - pandas=2.3.3=py310h0158d43_2
  - parso=0.8.5=py310h06a4308_0
  - pexpect=4.9.0=py310h06a4308_1
  - pigz=2.8=h421ea60_2
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py310h06a4308_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.52=py310h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.4.1=py310h47b2149_0
  - psutil=7.0.0=py310hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310h06a4308_0
  - py-xgboost=3.1.3=cuda129_pyhb96f994_0
  - pygments=2.19.2=py310h06a4308_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-gil=3.10.19=hd8ed1ab_3
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py310hf3bd8b6_1
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_1
  - pyzmq=27.1.0=py310hcf8288c_1
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=hc2a1206_0
  - regex=2026.1.15=py310h7c4b9e2_0
  - requests=2.32.5=pyhcf101f3_1
  - s2n=1.6.2=he8a4886_1
  - safetensors=0.7.0=py310hdfeec95_0
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.3=py310ha592af2_1
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=py310h06a4308_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py310h47b2149_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py310h3406613_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - alembic==1.18.4
      - antlr4-python3-runtime==4.8
      - captum==0.8.0
      - cffi==2.0.0
      - click==8.3.1
      - colorama==0.4.6
      - colorlog==6.10.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.2.4
      - einops==0.8.1
      - fairseq-signals==1.0.0a0+4e8278e
      - femr==0.2.4
      - filelock==3.20.1
      - fonttools==4.61.1
      - greenlet==3.3.1
      - grpcio==1.76.0
      - hydra-core==1.1.0
      - icecream==2.1.3
      - imageio==2.37.2
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lxml==6.0.2
      - mako==1.3.10
      - markdown==3.10.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - meds==0.3.3
      - meds-etl==0.3.6
      - meds-reader==0.1.14
      - mpmath==1.3.0
      - msgpack==1.1.2
      - networkx==3.4.2
      - nptyping==2.4.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.1.2
      - optuna==4.7.0
      - pandarallel==1.6.5
      - pandas-stubs==2.3.3.260113
      - pillow==12.0.0
      - pluggy==1.6.0
      - polars==1.37.1
      - polars-runtime-32==1.37.1
      - portalocker==3.2.0
      - protobuf==6.33.4
      - psycopg2-binary==2.9.11
      - pyarrow==23.0.0
      - pycparser==3.0
      - pyparsing==3.3.2
      - pytest==9.0.2
      - python-dotenv==1.2.1
      - referencing==0.37.0
      - rpds-py==0.30.0
      - sacrebleu==2.6.0
      - sacremoses==0.1.1
      - scikit-image==0.25.2
      - seaborn==0.13.2
      - soundfile==0.13.1
      - sqlalchemy==2.0.46
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tifffile==2025.5.10
      - tokenizers==0.19.1
      - tomli==2.4.0
      - torch==2.9.1
      - torch-hawk==0.0.8
      - torchvision==0.24.1
      - torchxrayvision==1.4.0
      - tqdm==4.67.1
      - transformers==4.41.2
      - triton==3.5.1
      - types-pytz==2025.2.0.20251108
      - types-requests==2.32.4.20260107
      - types-tqdm==4.67.0.20250809
      - werkzeug==3.1.5
      - wfdb==4.3.0
      - xformers==0.0.33.post2
      - zstandard==0.25.0
prefix: /home/pc/miniconda3/envs/thesis_py310
