name: thesis_py310
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py310h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - comm=0.2.3=py310h06a4308_0
  - cuda-version=12.9=h4f385c5_3
  - debugpy=1.8.16=py310hbdd6827_1
  - decorator=5.2.1=py310h06a4308_0
  - exceptiongroup=1.3.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ipykernel=6.31.0=py310h7040dfc_0
  - ipython=8.30.0=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.6.3=py310h06a4308_1
  - jupyter_core=5.9.1=py310h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=h4751f2c_7
  - liblapack=3.11.0=5_h47877c9_openblas
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxgboost=3.1.3=cuda129_h54c741a_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=py310h06a4308_0
  - nccl=2.29.2.1=h4d09622_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=py310h06a4308_1
  - parso=0.8.5=py310h06a4308_0
  - pexpect=4.9.0=py310h06a4308_1
  - pigz=2.8=h421ea60_2
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py310h06a4308_0
  - prompt-toolkit=3.0.52=py310h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310h06a4308_0
  - py-xgboost=3.1.3=cuda129_pyhb96f994_0
  - pygments=2.19.2=py310h06a4308_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python_abi=3.10=2_cp310
  - pyzmq=27.1.0=py310hcf8288c_1
  - readline=8.3=hc2a1206_0
  - scikit-learn=1.7.2=py310h228f341_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=py310h06a4308_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py310h47b2149_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - wcwidth=0.2.13=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - datasets==4.5.0
      - dill==0.4.0
      - einops==0.8.1
      - femr==0.2.4
      - filelock==3.20.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - greenlet==3.3.1
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - icecream==2.1.3
      - idna==3.11
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - markdown==3.10.1
      - markupsafe==3.0.3
      - meds==0.3.3
      - meds-etl==0.3.6
      - meds-reader==0.1.14
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - nptyping==2.4.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - pandas==2.3.3
      - pandas-stubs==2.3.3.260113
      - pillow==12.0.0
      - pluggy==1.6.0
      - polars==1.37.1
      - polars-runtime-32==1.37.1
      - propcache==0.4.1
      - protobuf==6.33.4
      - psycopg2-binary==2.9.11
      - pyarrow==23.0.0
      - pytest==9.0.2
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scipy==1.15.3
      - sqlalchemy==2.0.46
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tokenizers==0.22.2
      - tomli==2.4.0
      - torch==2.9.1
      - torch-hawk==0.0.8
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.6
      - triton==3.5.1
      - types-pytz==2025.2.0.20251108
      - types-requests==2.32.4.20260107
      - types-tqdm==4.67.0.20250809
      - tzdata==2025.3
      - urllib3==2.6.3
      - werkzeug==3.1.5
      - xformers==0.0.33.post2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /home/pc/miniconda3/envs/thesis_py310
